name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://wrjonline-my.sharepoint.com/personal/wwrrj_wrjonline_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fwwrrj%5Fwrjonline%5Fonmicrosoft%5Fcom%2FDocuments%2F%E7%B1%BB%E5%8E%9F%E7%94%9F%2F16sPro%2FPixelExperience%5Fm1973%2D11%2E0%2D20210722%2D1329%2DUNOFFICIAL%2Ezip&parent=%2Fpersonal%2Fwwrrj%5Fwrjonline%5Fonmicrosoft%5Fcom%2FDocuments%2F%E7%B1%BB%E5%8E%9F%E7%94%9F%2F16sPro&originalPath=aHR0cHM6Ly93cmpvbmxpbmUtbXkuc2hhcmVwb2ludC5jb20vOnU6L2cvcGVyc29uYWwvd3dycmpfd3Jqb25saW5lX29ubWljcm9zb2Z0X2NvbS9FV015YVdRektDeFBqN1pvQ3NudERZSUJGS0RzRTFSbDhpNGJYWG00NHZtWVZRP3J0aW1lPUtMNzRlV3BSMlVn
  ROM_NAME: PixelExperience
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof final/GSI.zip

         
            
